swipe:
  3:
    left:
      command: 'xdotool key ctrl+alt+Down'
    right:
      command: 'xdotool key ctrl+alt+Up'
    up:
      command: 'xdotool key super'
    down:
      command: 'xdotool key super'
  4:
    left:
      command: 'xdotool key ctrl+alt+Down'
    right:
      command: 'xdotool key ctrl+alt+Up'
    up:
      command: 'xdotool key super'
    down:
      command: 'xdotool key super'

threshold:
  swipe: 0.3
  pinch: 0.1

interval:
  swipe: 1
  pinch: 1
